# Generated by Django 4.2 on 2024-07-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0003_vet_created_at_vet_discharge_date_vet_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vet',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vet',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vet',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Macho'), ('F', 'Hembra')], max_length=1, null=True),
        ),
    ]
