# Generated by Django 4.2 on 2024-07-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0004_vet_edad_vet_peso_vet_phone_number_vet_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='edad',
            field=models.TextField(blank=True, null=True),
        ),
    ]
